name: Playground

on:
  push:
    branches: master
  workflow_dispatch:

env:
  IMAGE_NAME: mcr.microsoft.com/windows/nanoserver:ltsc2022


jobs:
  build:
    runs-on: windows-2022
    name: Test container on Windows

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker build
        run: |
          docker build -t msys2-ltsc2022 --build-arg=OS=ltsc2022 docker
