name: Playground

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    name: Windows Image ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: windows-msys2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image }}/
          file: ./${{ matrix.image }}/Dockerfile
          build-args: |
            GIT_COMMIT_HASH=${{ github.sha }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/workrave-build:${{ matrix.image }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
