name: Playground

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    name: Windows Image ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: windows-msys2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t ${{ github.repository_owner }}/workrave-build:${{ matrix.image }} --build-arg=GIT_COMMIT_HASH=${{ github.sha }} ./${{ matrix.image }}/

      - name: Publish
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/workrave-build:${{ matrix.image }}
